apiVersion: v1
kind: Service
metadata:
  name: backend-cristhoper-socalay-service
  namespace: cristhoper-socalay
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30001
  selector:
    app: backend-cristhoper-socalay