apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cristhoper-socalay-deployment
  namespace: cristhoper-socalay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-cristhoper-socalay
  template:
    metadata:
      labels:
        app: backend-cristhoper-socalay
    spec:
      containers:
        - name: prs-backend
          image: cris2003/backprs:latest
          ports:
            - containerPort: 8085
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DATABASE_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi