apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  DATABASE_URL: "r2dbc:postgresql://ep-long-tree-a567yxy3.us-east-2.aws.neon.tech/neondb?sslmode=require"
  DATABASE_USERNAME: "neondb_owner"
  DATABASE_PASSWORD: " RPxZWiQy69vE"

